### ISSUE TITLE
TypeError: Cannot read property 'findEachPhoto' of undefined

### ISSUE THREAD

**Issue by rjhale1971** [fulcrumapp/fulcrum-desktop#11]
I'm building this on Ubuntu 16.04 and with PostGIS 2.4 and postgresql 9.6. This is a barebones install - so the only thing this VM has on it is Postgres and Fulcrum Desktop. 

When I do this: 
 /opt/Fulcrum/scripts/fulcrum postgres --org 'organization' --pg-database 'fulcrumapp' 

I get this: 
Inititalizing database...
Populating system tables...
TypeError: Cannot read property 'findEachPhoto' of undefined
    at /home/rjhale/.fulcrum/plugins/fulcrum-desktop-postgres/plugin.js:665:11
    at Generator.next (<anonymous>)
    at step (/home/rjhale/.fulcrum/plugins/fulcrum-desktop-postgres/dist/plugin.js:47:191)
    at /home/rjhale/.fulcrum/plugins/fulcrum-desktop-postgres/dist/plugin.js:47:437
    at /home/rjhale/.fulcrum/plugins/fulcrum-desktop-postgres/dist/plugin.js:47:99
    at exports.default.setupSystemTables (/home/rjhale/.fulcrum/plugins/fulcrum-desktop-postgres/plugin.js:660:36)
    at /home/rjhale/.fulcrum/plugins/fulcrum-desktop-postgres/plugin.js:772:20
    at Generator.next (<anonymous>)
    at step (/home/rjhale/.fulcrum/plugins/fulcrum-desktop-postgres/dist/plugin.js:47:191)
    at /home/rjhale/.fulcrum/plugins/fulcrum-desktop-postgres/dist/plugin.js:47:361
    at process._tickCallback (internal/process/next_tick.js:103:7)

BUT - it will sync. I'm just wondering if this is causing an issue somewhere (or is there something I should look at or fix.

**Comment by zhm** [comment]
This happens when the account has not been setup yet using `fulcrum setup` or the `--org` parameter is a non-existent account. It's not necessary use the `fulcrum postgres` command anymore.

You just need to:

1. Install the executable
2. `fulcrum install-plugin --name postgres`
3. Create a postgres database named `fulcrumapp` with postgis enabled
4. `fulcrum setup`
5.  `fulcrum sync --org NAME --pg-database fulcrumapp

If this pops up again feel free to re-open the issue!
