### ISSUE TITLE
Gracefully handling self-signed certificate chains

### ISSUE THREAD

**Issue by csomerlot** [fulcrumapp/fulcrum-desktop#18]
My company switched to using self-signed certificates, which are in the Windows store, but many app don't use that so we have to find work-arounds. For getting Node to use a specific certificate we can set the env var NODE_TLS_REJECT_UNAUTHORIZED to 0, but yarn does not appear to have a place to configure this, so the plugin installs crash. I suggest you add an option to the setup for a certificate to use in all the places its needed.

fulcrum-desktop-postgres Cloning...
fulcrum-desktop-postgres Installing dependencies...
fulcrum-desktop-postgres yarn install v0.23.3
fulcrum-desktop-postgres [1/4] Resolving packages...
fulcrum-desktop-postgres [2/4] Fetching packages...
fulcrum-desktop-postgres error An unexpected error occurred: "https://registry.yarnpkg.com/pg/-/pg-6.1.5.tgz: SSL Error: SELF_SIGNED_CERT_IN_CHAIN".

**Comment by tylerjohnst** [comment]
`yarn config set "strict-ssl" false`

That being said, disabling strict SSL has all sorts of security implications. Use at your own risk.

**Comment by csomerlot** [comment]
Where would that even go?

**Comment by zhm** [comment]
You can try putting this in a file named `~/.yarnrc`

```
cafile "/path/to/my/cert.pem"
```

There's some more info here:

* https://github.com/yarnpkg/yarn/issues/2541
* https://github.com/yarnpkg/yarn/issues/841
* https://stackoverflow.com/questions/39984336/how-do-i-modify-the-configuration-of-yarn

I'm going to close this because it's an environment issue and I don't believe we're doing anything out of the ordinary with respect to SSL in Desktop. It would be better to find a solution with the system administrator or whatever is requiring the non-standard cert chain configuration.
