### ISSUE TITLE
Fulcrum 0.0.75 with postgresql plugin not working: error is date type field

### ISSUE THREAD

**Issue by needeco** [fulcrumapp/fulcrum-desktop#25]
I am using Postgresql 11 and Fulcrum 0.0.75. Fulcrum desktop is working fine until postgresql plugin not get installed. After installing this plugin i try to run sync command i am gettiong following error:

C:\Users\XXXX\Fulcrum\scripts>fulcrum sync --org     ........
Inititalizing database...
Populating system tables...
Migrating date calculation fields...
Migrating date calculation fields in form... ABCD Project forms
Migrating date calculation fields in form... ABCD_Timesheets
error: invalid input syntax for type date: "1.5"
    at Connection.parseE (C:\Users\XXXX\.fulcrum\plugins\fulcrum-desktop-postgres\node_modules\pg\lib\connection.js:569:11)
    at Connection.parseMessage (C:\Users\XXXX\.fulcrum\plugins\fulcrum-desktop-postgres\node_modules\pg\lib\connection.js:396:17)
    at Socket.<anonymous> (C:\Users\XXXX\.fulcrum\plugins\fulcrum-desktop-postgres\node_modules\pg\lib\connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)

Please let em know if you need any other information to resolve my issue.
Thanks

**Comment by zhm** [comment]
Thanks for reporting this issue. I think this is caused by having invalid data in a date-formatted calculation field. This can happen if you create a calculation field using the text format (any value) and put `"1.5"` into some records, and then after creating some records modify the calculation field format to use the date format. It's not able to convert `"1.5"` to a date type. While we work out a permanent fix, the options are to update the problematic records to fix the data, or to change the calculation field to a text format.

**Comment by needeco** [comment]
Thanks zhm, i am updating field type for problamatic records for now:)

**Comment by zhm** [comment]
I've pushed an update to the plugin which should fix this issue permanently. It will attempt to cast the invalid data to a date as best it can, and fall back to a `NULL` when it cannot properly cast it. Thanks for the bug report!

**Comment by needeco** [comment]
Thanks for quick reply and fixing my issue.
